version: '3'
services:
  redis:
    image: 'redis:latest'
    command: ['redis-server', '--appendonly', 'yes']
    volumes:
      - 'redis-data:/data'
    ports:
      - '6379:6379'
  app:
    build: .
    ports:
      - '8080:8080'
    environment:
      - REDIS_ADDR=redis:6379
    depends_on:
      - redis
volumes:
  redis-data: